/**
 * B2C Consumer Cooperative — official membership form (digital capture).
 * Mirrors the Board-approved sheet: acknowledgement, personal, parents, addresses,
 * registrations, spouse, employment, income, banks, assets, children, approval refs.
 */

export function createEmptyMemberProfile() {
  return {
    formTitle: "MEMBERSHIP FORM",
    cooperative: {
      name: "B2C CONSUMER COOPERATIVE",
      address: "",
      emailAddress: "",
      telephoneNumber: "",
    },
    acknowledgement: {
      consentToDataProcessing: false,
      memberSignatureOverPrintedName: "",
    },
    personal: {
      memberIdNo: "",
      /** Optional; validated server-side. Alternate to default lastname-seq handle. */
      callsign: "",
      lastName: "",
      firstName: "",
      middleName: "",
      suffixName: "",
      nickname: "",
      birthDate: "",
      /** Combined display: "City/Municipality, Province" (synced from PSGC dropdowns). */
      placeOfBirth: "",
      /** PSGC province code (3-digit string, e.g. "022"); pairs with placeOfBirthMunCity. */
      placeOfBirthProvCode: "",
      /** City or municipality name within placeOfBirthProvCode. */
      placeOfBirthMunCity: "",
      countryOfBirth: "",
      civilStatus: "",
      sexGender: "",
      bloodType: "",
      heightFeetInches: "",
      weightKg: "",
      noOfChildren: "",
      noOfDependents: "",
      citizenshipNationality: "",
      religion: "",
      socialAffiliations: "",
      highestEducation: "",
    },
    mother: {
      maidenLastName: "",
      maidenFirstName: "",
      maidenMiddleName: "",
      region: "",
      province: "",
      cityMunicipality: "",
      barangay: "",
      streetSubdivision: "",
      postalCode: "",
    },
    father: {
      lastName: "",
      firstName: "",
      middleName: "",
      suffix: "",
      region: "",
      province: "",
      cityMunicipality: "",
      barangay: "",
      streetSubdivision: "",
      postalCode: "",
    },
    presentAddress: {
      country: "",
      region: "",
      province: "",
      cityMunicipality: "",
      barangay: "",
      subdivision: "",
      street: "",
      houseNo: "",
      postalCode: "",
      occupiedSince: "",
      livingWithParents: "",
      rentedHouse: "",
      ownedHouse: "",
      houseOwnerIfRented: "",
    },
    previousAddress: {
      country: "",
      region: "",
      province: "",
      cityMunicipality: "",
      barangay: "",
      subdivision: "",
      street: "",
      houseNo: "",
      postalCode: "",
      periodDateFrom: "",
      periodDateTo: "",
    },
    contact: {
      homePhoneAreaCode: "",
      homePhoneNo: "",
      mobileNo: "",
      officePhoneAreaCode: "",
      officePhoneNo: "",
      emailAddress: "",
    },
    registrationNoExpiry: {
      tinNo: "",
      sssNo: "",
      gsisNo: "",
      umidNo: "",
      philhealthOrPagibigNo: "",
      seniorCitizenCard: "",
    },
    registrationWithExpiry: {
      driversLicenseNo: "",
      driversLicenseIssuedDate: "",
      driversLicenseExpiryDate: "",
      passportIdNo: "",
      passportIssuedDate: "",
      passportExpiryDate: "",
      prcIdNo: "",
      prcIdIssuedDate: "",
      prcIdExpiryDate: "",
      postalIdNo: "",
      postalIdIssuedDate: "",
      postalIdExpiryDate: "",
    },
    spouse: {
      lastName: "",
      firstName: "",
      middleName: "",
      maidenName: "",
      companyName: "",
      employerAddress: "",
      officePhoneNo: "",
      mobileNo: "",
      emailAddress: "",
    },
    employment: {
      company: "",
      sector: "",
      region: "",
      province: "",
      cityMunicipality: "",
      barangay: "",
      streetSubdivision: "",
      postalCode: "",
      companyIdNo: "",
      position: "",
      jobLevel: "",
      employmentStatus: "",
      yearsOfEmployment: "",
      dateHiredFrom: "",
      dateHiredTo: "",
    },
    selfEmployment: {
      sector: "",
      subSector: "",
      occupation: "",
      businessName: "",
      lineOfBusiness: "",
      region: "",
      province: "",
      cityMunicipality: "",
      barangay: "",
      streetSubdivision: "",
      postalCode: "",
    },
    income: {
      salaryAnnual: "",
      businessIncomeAnnual: "",
      otherIncomeAnnual: "",
      spouseSalaryAnnual: "",
      spouseBusinessIncomeAnnual: "",
    },
    bankAccounts: [
      { bankName: "", accountType: "" },
      { bankName: "", accountType: "" },
      { bankName: "", accountType: "" },
    ],
    assets: {
      carOwned1: "",
      carOwned2: "",
      carOwned3: "",
      carOwned4: "",
      carOwned5: "",
      otherAssets1: "",
      otherAssets2: "",
      otherAssets3: "",
      otherAssets4: "",
      otherAssets5: "",
    },
    membershipApproval: {
      approved: false,
      disapproved: false,
      deferred: false,
      boardResolutionNo: "",
      boardResolutionDate: "",
      boardSecretaryName: "",
      memberNotes: "Member completes data entry; Board action is recorded by staff in admin records.",
    },
    childrenDependents: [
      { nameOfChildDependent: "", birthDate: "" },
      { nameOfChildDependent: "", birthDate: "" },
      { nameOfChildDependent: "", birthDate: "" },
      { nameOfChildDependent: "", birthDate: "" },
      { nameOfChildDependent: "", birthDate: "" },
      { nameOfChildDependent: "", birthDate: "" },
    ],
    signature: {
      memberSignatureOverPrintedName: "",
      date: "",
    },
    internalNotes: "",
  };
}
